# Generated by Django 3.2.6 on 2021-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbangreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Arrivals',
            new_name='ug_new_arrivals',
        ),
    ]
